/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/schema/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json */
    get: operations['api_schema_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/info/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_auth_info_retrieve'];
    put?: never;
    post: operations['v1_auth_info_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_auth_login_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_auth_logout_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/status/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_auth_status_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/classify/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['v1_classify_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/classify/{id}/{index}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_classify_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/datasets/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_datasets_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/datasets/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_datasets_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/datasets/{id}/{index}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The file at the index of the dataset */
    get: operations['v1_datasets_retrieve_entry'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/export/{study}/csv/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description A QR code linking to this study */
    get: operations['v1_export_csv_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/share/{study}/anonymous/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description A QR code linking to this study with an authorization for anonymous access */
    get: operations['v1_share_anonymous_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/share/{study}/users/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description A QR code linking to this study */
    get: operations['v1_share_users_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studies/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_studies_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studies/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_studies_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studies/{id}/{index}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The file at the index of the dataset based on the user */
    get: operations['v1_studies_retrieve_entry'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studies/{id}/postponed/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['v1_studies_postponed_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {unknown} */
    BlankEnum: '';
    /**
         * @description * `up` - up
         *     * `down` - down
         *     * `left` - left
         *     * `right` - right
         * @enum {string}
         */
    ChoiceEnum: 'up' | 'down' | 'left' | 'right';
    ClassifyInput: {
      /** Format: uuid */
      study: string;
      choice: components['schemas']['ChoiceEnum'];
      index: number;
    };
    ClassifyOutput: {
      /** Format: uuid */
      study: string;
      choice: string;
      index: number;
      readonly education: components['schemas']['Education'] | null;
    };
    Dataset: {
      /** Format: uuid */
      readonly id: string;
      /** @description Only used for display purposes in the study creation. */
      title: string;
      /**
             * Format: uri
             * @description The dataset archive. Files are registered by their full path inside the archive.
             */
      archive: string;
      /**
             * Format: int64
             * @description The number of files in the dataset. Calculated automatically.
             */
      file_count?: number | null;
      /** @description A list of all files in the dataset. Calculated automatically. */
      file_list?: unknown;
    };
    Detail: {
      detail: string;
    };
    Education: {
      solution: components['schemas']['Solution'];
      proof: string | null;
    };
    Error: {
      detail: string;
    };
    InfoRequest: {
      intro_general?: number;
      intro_swiping?: number;
    };
    InfoResponse: {
      intro_general: number;
      intro_swiping: number;
    };
    Login: {
      username: string;
      password: string;
    };
    /** @enum {unknown} */
    NullEnum: null;
    /**
         * @description * `left` - left
         *     * `right` - right
         *     * `up` - up
         *     * `down` - down
         * @enum {string}
         */
    PostponeEnum: 'left' | 'right' | 'up' | 'down';
    Postponed: {
      images: number[];
    };
    Solution: {
      /** @default  */
      text: string;
      /** @default  */
      choice: string;
    };
    SolutionConfig: {
      /** @description (optional) The label displayed for the classified image. Defaults to 'Current' in the frontend. */
      label_current?: string | null;
      /** @description (optional) The label displayed for the proof. Defaults to 'Proof' in the frontend. */
      label_proof?: string | null;
      /** @description (optional) The CSS class for the row. Overrides the frontend defaults. */
      css_row?: string | null;
      /** @description (optional) The CSS class for the column. Additional modifiers that are added to the frontend defaults. */
      css_column?: string | null;
    };
    Status: {
      authenticated: boolean;
      username: string;
    };
    Study: {
      /** Format: uuid */
      readonly id: string;
      /** @description The title of the study. Visible in all interfaces. */
      title: string;
      /** @description (optional) A short description of the study. Markdown is supported. */
      description?: string | null;
      /**
             * Format: uri
             * @description (optional) A title image for the study.
             */
      image?: string | null;
      /**
             * Start
             * Format: date-time
             * @description The study will be visible on the overview at this time.
             */
      pub_date: string;
      /**
             * End
             * Format: date-time
             * @description The study will be removed from the overview at this time.
             */
      end_date: string;
      readonly educational: boolean;
      length: number;
      readonly index: number;
      solution: components['schemas']['SolutionConfig'] | null;
      ui: components['schemas']['Ui'];
    };
    StudyList: {
      /** Format: uuid */
      readonly id: string;
      /** @description The title of the study. Visible in all interfaces. */
      title: string;
      /** @description (optional) A short description of the study. Markdown is supported. */
      description?: string | null;
      /**
             * Format: uri
             * @description (optional) A title image for the study.
             */
      image?: string | null;
      /**
             * Start
             * Format: date-time
             * @description The study will be visible on the overview at this time.
             */
      pub_date: string;
      /**
             * End
             * Format: date-time
             * @description The study will be removed from the overview at this time.
             */
      end_date: string;
      readonly educational: boolean;
      length: number;
      readonly index: number;
    };
    Ui: {
      /** @description Only used for display purposes in the study creation. */
      title: string;
      labels: components['schemas']['UiLabel'];
      /** @description (optional) The direction to mark images for another round of classification.
             *
             *     * `left` - left
             *     * `right` - right
             *     * `up` - up
             *     * `down` - down */
      postpone?: (components['schemas']['PostponeEnum'] | components['schemas']['BlankEnum'] | components['schemas']['NullEnum']) | null;
      /** @description Use 'pixelated' image-rendering. */
      pixelated?: boolean;
      /**
             * Format: int64
             * @description The default scale of images in the study. Values in percent.
             */
      default_scale?: number;
    };
    UiDirection: {
      text: string | null;
      color: string | null;
      icon: string | null;
    };
    UiLabel: {
      left: components['schemas']['UiDirection'] | null;
      right: components['schemas']['UiDirection'] | null;
      up: components['schemas']['UiDirection'] | null;
      down: components['schemas']['UiDirection'] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  api_schema_retrieve: {
    parameters: {
      query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.oai.openapi': {
            [key: string]: unknown;
          };
          'application/yaml': {
            [key: string]: unknown;
          };
          'application/vnd.oai.openapi+json': {
            [key: string]: unknown;
          };
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  v1_auth_info_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InfoResponse'];
        };
      };
    };
  };
  v1_auth_info_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['InfoRequest'];
        'application/x-www-form-urlencoded': components['schemas']['InfoRequest'];
        'multipart/form-data': components['schemas']['InfoRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InfoResponse'];
        };
      };
    };
  };
  v1_auth_login_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Login'];
        'application/x-www-form-urlencoded': components['schemas']['Login'];
        'multipart/form-data': components['schemas']['Login'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  v1_auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Detail'];
        };
      };
    };
  };
  v1_auth_status_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Status'];
        };
      };
    };
  };
  v1_classify_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClassifyInput'];
        'application/x-www-form-urlencoded': components['schemas']['ClassifyInput'];
        'multipart/form-data': components['schemas']['ClassifyInput'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClassifyOutput'];
        };
      };
    };
  };
  v1_classify_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this study. */
        id: string;
        index: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClassifyOutput'];
        };
      };
    };
  };
  v1_datasets_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dataset'][];
        };
      };
    };
  };
  v1_datasets_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this dataset. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dataset'];
        };
      };
    };
  };
  v1_datasets_retrieve_entry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this dataset. */
        id: string;
        index: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
    };
  };
  v1_export_csv_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        study: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/svg+xml': string;
        };
      };
    };
  };
  v1_share_anonymous_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        study: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/svg+xml': string;
        };
      };
    };
  };
  v1_share_users_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        study: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/svg+xml': string;
        };
      };
    };
  };
  v1_studies_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StudyList'][];
        };
      };
    };
  };
  v1_studies_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this study. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Study'];
        };
      };
    };
  };
  v1_studies_retrieve_entry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this study. */
        id: string;
        index: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
    };
  };
  v1_studies_postponed_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this study. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Postponed'];
        };
      };
    };
  };
}
