/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FetchError: typeof import('./components/FetchError.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageSwiper: typeof import('./components/ImageSwiper.vue')['default']
    PastDecision: typeof import('./components/PastDecision.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudyDescription: typeof import('./components/StudyDescription.vue')['default']
    StudySolution: typeof import('./components/StudySolution.vue')['default']
    SwanIcon: typeof import('./components/SwanIcon.vue')['default']
    SwiperHelp: typeof import('./components/SwiperHelp.vue')['default']
    SwiperToolbar: typeof import('./components/SwiperToolbar.vue')['default']
  }
}
